name: CI

on: 
  push:
    branches: [ main, dev ]
  pull_request: 
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test
  deploy-dev:
    needs: build-test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying to ${{ vars.STAGE}}"
          echo "Devs api key is ${{ secrets.}}"


        
